name: Build and deploy Project Zoe client

on:
  push:
    branches: [ master, develop, feature/worship-harvest ]
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      # For some strange reason, npm 8.x fails so sticking to this for now
      - name: Install npm 6.14.5
        run: |
          npm install -g npm@6.14.5 &&
          npm --version 

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: |
          npm install   
          
    #- name: Run the tests and generate coverage report
    #  run: npm test -- --coverage
#
    #- name: Upload coverage to Codecov
    #  uses: codecov/codecov-action@v1
          
      # Temporarily skip eslint by using DISABLE_ESLINT_PLUGIN
      - name: Build
        run: |
          DISABLE_ESLINT_PLUGIN=true npm run build

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$DO_PRIVATE_KEY" > ~/.ssh/project-zoe-prod-1.key
          chmod 600 ~/.ssh/project-zoe-prod-1.key
          cat >>~/.ssh/config <<END
          Host project-zoe-prod-1
            HostName $DO_HOST
            User $DO_USERNAME
            IdentityFile ~/.ssh/project-zoe-prod-1.key
            StrictHostKeyChecking no
          END
        env:
          DO_USERNAME: ${{ secrets.DO_USERNAME }}
          DO_PRIVATE_KEY: ${{ secrets.DO_PRIVATE_KEY }}
          DO_HOST: ${{ secrets.DO_HOST }}

      - name: Deploy the app
        run: rsync -rtvO ./dist/ project-zoe-prod-1:/opt/project-zoe-server/dist/

      - name: Run the app
        run: ssh project-zoe-prod-1 'cd /opt/project-zoe-server/dist/ && pm2 delete zoeServer  2> /dev/null || true && production=true pm2 start dist/main.js --name zoeServer'
            
 
